# Generated by Django 6.0.4 on 2026-04-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('assistant', 'Assistant')], db_index=True, max_length=16)),
                ('student_id', models.CharField(db_index=True, help_text="Identifies the student in the session. May be anonymised (e.g. 'TOM', 'PRIYA').", max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('year_group', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'sender_type'], name='bridewell_a_timesta_b4673b_idx'), models.Index(fields=['student_id', 'timestamp'], name='bridewell_a_student_156f21_idx')],
            },
        ),
    ]
